helm_deploy/hmpps-digital-prison-reporting-mi-ui/values.yaml

White List Health Check Team

---

helm_deploy/hmpps-digital-prison-reporting-mi-ui/values.yaml

Include New IT Health Check IP to allow List,

Update Allow List

---

audit-ci.json
docker-compose.yml
server/components/filters/utils.ts
server/routes/reports.test.ts
server/routes/reports.ts
server/types/reports/class.ts
server/utils/urlHelper.test.ts
server/utils/urlHelper.ts

Additionally:
- Docker compose tweak, to use dev env over local docker instances of dependencies.
- Downgrade OWASP checking to moderate or higher (rather than low or higher).

[DPR-576] Fix for filters not staying when changing page

---

assets/scss/components/_data-table.scss
audit-ci.json
integration_tests/mockApis/reports.ts
server/components/data-table/types.d.ts
server/components/data-table/utils.ts
server/config.ts
server/data/reportingClient.ts
server/routes/reportConfig/externalMovements.ts
server/routes/reports.test.ts
server/types/reports/enum.ts
server/types/reports/index.d.ts

- Avoided scanning dev dependencies.
- Added ability to prevent word wrapping.

[DPR-630] Add prisoner name

---

server/app.ts
server/middleware/populateCurrentUrl.ts
server/views/partials/header.njk

[DPR-652] Phase banner

---

server/components/report-list/utils.ts
server/data/reportingClient.test.ts
server/data/reportingClient.ts
server/data/restClient.ts
server/routes/reports.ts
server/services/reportingService.ts
server/types/reports/class.ts
server/utils/urlHelper.test.ts
server/utils/urlHelper.ts

- Fixed issue with default variant field date range values not mapping to filters.
- Fixed passthrough of filter values to match new API.

[DPR2-71] Align UI with API expectations

---

.circleci/config.yml

This works around the issue of the APP_VERSION being cleared from the cache after 15 days, making it impossible to deploy or roll back after that time.

[DPR2-132] Use deterministic image tag

---

package-lock.json
package.json

Dpr2 336 bump frontend lib version

---

package-lock.json
package.json
server/routes/reports.ts

FE Version bump
"^2.3.0" => "^2.4.1",

fe version bump

---

assets/js/dprFrontendInit.js
package-lock.json
package.json

bump version

---

package-lock.json
package.json

Dpr2 432 bump fe version

---

package-lock.json
package.json
server/routes/index.ts
server/routes/reports.ts
server/views/partials/breadCrumb.njk
server/views/partials/header.njk

https://dsdmoj.atlassian.net/jira/software/c/projects/DPR2/boards/1282?selectedIssue=DPR2-466
- Removed current page from breadcrumb
- First breadcrumb is DPS

remove current page from breadcrumb. Add DPS as first breadcrunb

---

package-lock.json
package.json

bump fe version 3.6.0

---

package-lock.json
package.json

Dpr2 448 bump fe lib

---

package-lock.json
package.json

bump fe lib version 3.10.4 -> 3.11.0

bump fe lib version 3.10.4 -> 3.11.0

---

package-lock.json
package.json
server/routes/testutils/appSetup.ts

Bump FE Lib version 3.11.0 -> 3.12.0

Bump FE Lib version 3.11.0 -> 3.12.0

---

package-lock.json
package.json

bump version 3.12.3 -> 3.13.0

---

package-lock.json
package.json
server/middleware/populateCurrentUser.ts
server/middleware/setUpCurrentUser.ts
server/routes/index.test.ts
server/routes/index.ts
server/routes/reports.test.ts
server/services/index.ts
server/views/pages/home.njk

Bookmarking routes added the UI

bookmarking to UI

---

package-lock.json
package.json

bump FE version

---

package-lock.json
package.json

Dpr2 846 fe lib version bump

---

package-lock.json
package.json
server/middleware/populateCurrentUser.ts
server/routes/index.ts

- Bump FE version 
- Missing await in initialising services
- updated to use uuid instead of name when initialising services

bump verison

---

package-lock.json
package.json
server/routes/reports.test.ts
server/views/pages/home.njk

- Updated version from 3.15.11 => ^3.17.3
- Adde tabs to the homepage
- Updated test - not sure why this has changed. Needs further investigation as to whether this is expected

updated test

---

package-lock.json
package.json
server/routes/testutils/appSetup.ts

Bump FE lib version to 3.17.7

---

package-lock.json
package.json
server/routes/testutils/appSetup.ts

Dpr2 960 bump fe version to 3.17.8

---

server/middleware/authorisationMiddleware.test.ts
server/middleware/authorisationMiddleware.ts
server/middleware/populateCurrentUser.ts
server/services/userService.ts

- Reverted new role auth code in place of existing middleware
- Redirect to new error page

Consumer Roles redirect

---

package-lock.json
package.json

FE version bump  3.20.0 -> 3.21.0

FE version bump  3.20.0 -> 3.21.0

---

package-lock.json
package.json

Dpr2 916 version update

---

package-lock.json
package.json

FE lib version bump - 3.21.4

---

package-lock.json
package.json

FE Lib version bump to 3.22.0

---

server/data/hmppsManageUsersClient.ts
server/middleware/populateCurrentUser.ts
server/services/userService.ts

Fix for issue where requested reports aren't saved to a user and all requests are visible to all.

fix user issue

---

package-lock.json
package.json

FE Lib version bump to 3.22.2

---

package-lock.json
package.json
server/routes/index.ts

Dpr2 fe lib version bump

---

cypress-tests/acceptance-tests/step-definitions/common.ts
cypress-tests/common/pages/index.ts
package-lock.json
package.json
server/routes/index.test.ts
server/routes/index.ts

FE lib version bump to 3.23.0

---

package-lock.json
package.json

Bump FE lib version to 3.23.2

---

assets/js/dprFrontendInit.js
package-lock.json
package.json
server/data/index.ts
server/routes/index.ts
server/services/index.ts
server/views/pages/home.njk

- Integrated dashboards into ui
- Bumped FE lib version

Integrated dashboards

---

package-lock.json
package.json

bump lib - 3.26.2

---

server/middleware/siteMaintenanceRedirect.ts
server/services/userService.test.ts
server/services/userService.ts

- Fix error when user has no roles.
- Fix maintenance screen redirect when user is not logged in

[DPR2-1245] Post-release fixes

---

package-lock.json
package.json
server/middleware/setUpStaticResources.ts
server/middleware/setUpWebSecurity.ts
server/routes/index.ts
server/views/partials/layout.njk

- Bump FE lib
- Fix missing dayjs error

bump lib version

---

assets/js/mojFrontendInit.js
server/routes/index.ts
server/views/partials/layout.njk

fix moj init

---

package-lock.json
package.json
server/routes/index.ts

- Integrate download routes
- Bump FE Lib to 3.26.19

Add downlaod routes + bump FE lib version

---

package-lock.json
package.json

DPR2-1568 update lib

---

package-lock.json
package.json

Upgrade FE lib.
Upgraded Node to 22 and npm to 11.

DPR2-1587 upgrade node to 22 and npm to 11

---

server/app.ts
server/middleware/getFrontendComponents.test.ts
server/middleware/getFrontendComponents.ts

Fix 'token' of undefined bug in getFrontendComponents MW - https://dsdmoj.atlassian.net/browse/DPR2-2213

fix undefined error

---

package-lock.json
package.json

Bump lib 4.13 - save sort values as defaults
